from abc import ABC, abstractmethod
import pandas as pd

class DataProvider(ABC):
    @abstractmethod
    def start_stream(self): ...
    @abstractmethod
    def stop_stream(self): ...
    @abstractmethod
    def subscribe_bars(self, callback, tickers: list[str]): ...
    @abstractmethod
    def unsubscribe_bars(self, tickers: list[str]): ...
    @abstractmethod
    async def historical_df(self, symbol: str, start, end, timeframe: str="1Min") -> pd.DataFrame: ...
