"""
OHLCV bar response schema. Used by /api/v1/bars and (in FE-CONTRACTS-7)
the WebSocket `bars.{symbol}` topic.

Wire shape preserved byte-for-byte from the legacy /api/bars response
to keep the static HTML pages working through the transition:

  - `ts` is a string (ISO 8601 with `Z`) — generated by the legacy
    `_ts()` helper.
  - The route returns a bare `list[Bar]` (not Page[Bar]). Promotion
    to Page[Bar] is deferred to a follow-on phase that updates the
    static-HTML consumers in the same change.
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Bar(BaseModel):
    """A single OHLCV bar served from the ClickHouse live tier."""

    ts: str = Field(
        ...,
        description="ISO 8601 timestamp with `Z` suffix (e.g. '2026-05-18T20:55:00Z'). String, not datetime, so naive ClickHouse timestamps serialize exactly as the legacy `_ts()` helper produced them.",
    )
    open: float
    high: float
    low: float
    close: float
    volume: float = Field(
        ..., description="Trade volume during the bar. 0 for daily bars before regular session hours where no trades occurred."
    )

    # Optional metadata. These are populated when available from the
    # reader; null otherwise. The legacy /api/bars route stripped them
    # so cockpit consumers must treat them as truly optional.
    vwap: Optional[float] = Field(
        default=None,
        description="Volume-weighted average price for the bar (when available; null for resampled bars).",
    )
    trade_count: Optional[int] = Field(
        default=None,
        description="Number of trades in the bar (when available; null for resampled bars).",
    )
    source: Optional[str] = Field(
        default=None,
        description="Source table that served this bar: 'ohlcv_1m', 'ohlcv_5m', 'ohlcv_daily', or 'live'. Null when source-table tracking is not propagated.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ts": "2026-05-18T20:55:00Z",
                "open": 297.34,
                "high": 297.47,
                "low": 297.34,
                "close": 297.47,
                "volume": 2646.0,
                "vwap": None,
                "trade_count": None,
                "source": None,
            }
        }
    )
