"""initial tables

Revision ID: 361419077683
Revises: 
Create Date: 2025-10-03 11:53:06.404399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361419077683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ts', name='uq_bars_symbol_ts')
    )
    op.create_index(op.f('ix_bars_symbol'), 'bars', ['symbol'], unique=False)
    op.create_index('ix_bars_symbol_ts', 'bars', ['symbol', 'ts'], unique=False)
    op.create_index(op.f('ix_bars_ts'), 'bars', ['ts'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('signal_type', sa.String(length=64), nullable=True),
    sa.Column('indicator', sa.String(length=32), nullable=True),
    sa.Column('ts_signal', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_at_signal', sa.Float(), nullable=True),
    sa.Column('indicator_value', sa.Float(), nullable=True),
    sa.Column('p1_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('p2_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_ts', 'signals', ['symbol', 'ts_signal'], unique=False)
    op.create_index(op.f('ix_signals_ts_signal'), 'signals', ['ts_signal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_ts_signal'), table_name='signals')
    op.drop_index('ix_signals_symbol_ts', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_bars_ts'), table_name='bars')
    op.drop_index('ix_bars_symbol_ts', table_name='bars')
    op.drop_index(op.f('ix_bars_symbol'), table_name='bars')
    op.drop_table('bars')
    # ### end Alembic commands ###
