"""Pydantic contracts for the Assistant service.

The full specification of each type lives in
[docs/assistant_plan.md §5](../../../docs/assistant_plan.md). This
module is the single source of truth for the wire format; both the
HTTP/SSE layer and the storage layer build on these shapes.

Design rules (per `feedback_service_module_design`):
  - Schemas are frozen where the value is intrinsically immutable
    (events, finished turns). Mutable working state stays unfrozen.
  - Use `Literal` and `StrEnum` for type-safety on string fields the
    client filters on.
  - No business logic here — schemas describe shape only.
"""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, NonNegativeFloat, NonNegativeInt


class Role(StrEnum):
    """Who produced a conversation turn."""

    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    SYSTEM_NOTICE = "system_notice"


class ToolCallStatus(StrEnum):
    """Lifecycle of one tool invocation."""

    PENDING_CONFIRM = "pending_confirm"
    RUNNING = "running"
    OK = "ok"
    ERROR = "error"
    DENIED = "denied"
    CANCELLED = "cancelled"


class StreamEventType(StrEnum):
    """Wire-format tag for SSE events emitted during a turn."""

    TEXT_DELTA = "text_delta"
    TOOL_CALL_STARTED = "tool_call_started"
    TOOL_CALL_PENDING_CONFIRM = "tool_call_pending_confirm"
    TOOL_RESULT = "tool_result"
    TOOL_ERROR = "tool_error"
    ARTIFACT_READY = "artifact_ready"
    THINKING_DELTA = "thinking_delta"
    QUOTA_WARNING = "quota_warning"
    TURN_COMPLETED = "turn_completed"
    ERROR = "error"
    DONE = "done"


class ToolCall(BaseModel):
    """One tool invocation the model asked to make.

    Lifecycle:
      PENDING_CONFIRM (write tools only) → RUNNING → OK | ERROR
      or PENDING_CONFIRM → DENIED
      or RUNNING → CANCELLED
    """

    id: str = Field(..., description="Stable id within the conversation turn.")
    name: str = Field(..., description="MCP tool name (e.g. 'get_lake_freshness').")
    args: dict[str, Any] = Field(default_factory=dict)
    status: ToolCallStatus
    started_at: datetime | None = None
    finished_at: datetime | None = None
    result: dict[str, Any] | None = Field(
        None,
        description=(
            "The tool's response, Pydantic-dumped. Subject to "
            "server-side truncation (see plan §8.4) before being "
            "fed back to the LLM; the full untruncated body lives "
            "in the artifact store when relevant."
        ),
    )
    error: str | None = None
    artifact_refs: list[str] = Field(
        default_factory=list,
        description="Optional artifact ids materialized for this call.",
    )
    truncated: bool = Field(
        False,
        description="True iff `result` was truncated for the LLM context.",
    )


class ConversationTurn(BaseModel):
    """One turn = one role's contribution to a conversation.

    A user message produces one USER turn followed by one or more
    ASSISTANT turns interleaved with TOOL turns. `sequence` is
    monotonic within a conversation; it is assigned server-side.
    """

    id: str
    conversation_id: str
    sequence: NonNegativeInt
    role: Role
    content: str = Field(
        "",
        description="Text body. Always populated for USER/ASSISTANT/SYSTEM_NOTICE; empty for TOOL turns.",
    )
    tool_calls: list[ToolCall] = Field(default_factory=list)
    model: str | None = Field(
        None,
        description="Anthropic model id, populated for ASSISTANT turns only.",
    )
    tokens_in: NonNegativeInt | None = None
    tokens_out: NonNegativeInt | None = None
    cost_usd: NonNegativeFloat | None = None
    cache_hit: bool = False
    created_at: datetime
    parent_turn_id: str | None = Field(
        None,
        description="For regenerated branches: the user turn this re-runs from.",
    )


class Conversation(BaseModel):
    """Header row for a conversation. Turns are stored separately."""

    id: str
    owner_id: str = Field(
        ...,
        description=(
            "Tenant scope. Defaults to the dev-mode sentinel "
            "`default-tenant`; populated by auth middleware in SaaS mode "
            "(see frontend_plan.md §7.1)."
        ),
    )
    user_id: str = Field(
        ...,
        description="Per-user-in-tenant; `default-user` in dev mode.",
    )
    title: str | None = Field(
        None,
        description="Autogenerated from the first user/assistant exchange.",
    )
    created_at: datetime
    updated_at: datetime
    turn_count: NonNegativeInt = 0
    total_cost_usd: NonNegativeFloat = 0.0
    deleted_at: datetime | None = None


class AssistantStreamEvent(BaseModel):
    """One SSE event. Type-discriminated; payload shape varies by type.

    Frozen because events are emitted, never mutated downstream.
    """

    model_config = ConfigDict(frozen=True)

    type: StreamEventType
    payload: dict[str, Any] = Field(default_factory=dict)


class ContinueRequest(BaseModel):
    """Body of POST /cockpit/assistant/conversations/{id}/turn."""

    user_msg: str = Field(..., min_length=1)
    model: str | None = Field(
        None,
        description="Optional override; None → ModelRegistry default (Sonnet 4.6).",
    )
    use_extended_thinking: bool = Field(
        False,
        description="If true, switches the turn to Opus 4.7 with a thinking budget.",
    )
    client_request_id: str | None = Field(
        None,
        description=(
            "Idempotency key. Re-POSTing with the same id while a turn is "
            "in flight re-attaches to the existing stream instead of "
            "starting a new turn."
        ),
    )


class ConfirmRequest(BaseModel):
    """Body of POST /cockpit/assistant/conversations/{id}/confirm.

    Resumes a turn that paused on a pending_confirm write-tool call.
    """

    tool_call_id: str
    decision: Literal["confirm", "deny"]
    reason: str | None = Field(
        None,
        description="Optional user-supplied note (esp. for deny).",
    )


DEFAULT_TENANT_ID = "default-tenant"
"""Sentinel `owner_id` in dev mode. SaaS-mode middleware replaces this."""

DEFAULT_USER_ID = "default-user"
"""Sentinel `user_id` in dev mode. SaaS-mode middleware replaces this."""
